// Drizzle schema — the single source of truth for every table this app
// touches, split by ownership. Migrations are tracked for real: see
// drizzle.config.ts + drizzle/ — `0000_baseline` describes exactly what was
// already live (these tables were originally created by ad-hoc raw SQL /
// Better Auth's own Kysely-based `migrate` CLI, before this app adopted
// Drizzle) and was marked as already-applied in `drizzle.__drizzle_migrations`
// without re-running its CREATE TABLE statements. Any SCHEMA CHANGE from here
// on must go through `pnpm drizzle:generate` (writes a new migration file)
// then `pnpm drizzle:migrate` (applies it) — hand-editing this file without a
// matching migration will silently drift from the real database again.
//   - `authSchema` (re-exported below) is GENERATED by `pnpm auth:generate`
//     from the plugins configured in ../auth.ts (user, session, account,
//     verification, organization, member, invitation, plus our
//     `runtimeApiKeyHash`/`runtimeApiKeyPrefix` additionalFields). Regenerate
//     it after changing auth.ts's plugins, then run the migrate step above —
//     never hand-edit auth-schema.ts.
//   - `dataSources` / `dashboards` below are Lumen-owned.
import { boolean, check, index, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'

export * from './auth-schema'

export const dataSources = pgTable(
  'data_sources',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    name: text('name').notNull(),
    provider: text('provider').notNull(),
    config: jsonb('config').notNull(),
    isActive: boolean('is_active').notNull().default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('data_sources_one_active').on(t.isActive).where(sql`is_active`),
    check('data_sources_provider_check', sql`${t.provider} = ANY (ARRAY['cube'::text, 'dbt'::text])`),
  ],
)

export const dashboards = pgTable(
  'dashboards',
  {
    id: text('id').primaryKey(),
    organizationId: text('organization_id').notNull().default(''),
    title: text('title').notNull(),
    theme: text('theme').notNull().default('light'),
    definition: jsonb('definition').notNull(),
    compiledAt: timestamp('compiled_at', { withTimezone: true }),
    contentHash: text('content_hash'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('dashboards_organization_id').on(t.organizationId)],
)
