// SERVER-ONLY. Access to Cloudflare Workers bindings + secrets — see
// wrangler.jsonc for what's bound (Hyperdrive, vars) and `.dev.vars.example`
// for local secrets.
//
// `@cloudflare/vite-plugin` is enabled in ALL modes (dev AND build — see
// vite.config.ts), so the app always runs inside workerd/Miniflare and
// `cloudflare:workers`'s `env` is always real, backed by the same
// per-request mechanism the deployed Worker itself uses. There is no
// separate "local Node dev" runtime to bridge to, so unlike an earlier
// version of this file, there's no dynamic import + try/catch + fallback to
// `process.env` — just a plain top-level import.
//
// `Cloudflare.Env` comes from `worker-configuration.d.ts`, generated by
// `pnpm cf-typegen` (`wrangler types`) from wrangler.jsonc — regenerate it
// after changing bindings/vars there.
import { env } from 'cloudflare:workers'

export type CloudflareEnv = Cloudflare.Env

export const getBindings = (): CloudflareEnv => env
